export const EASE = [0.16, 1, 0.3, 1] as [
  number,
  number,
  number,
  number
];

export type VenueFeatureIcon =
  | "capacity"
  | "halls"
  | "workshops"
  | "wifi"
  | "parking"
  | "catering";

export const VENUE_FEATURES: {
  icon: VenueFeatureIcon;
  label: string;
  value: string;
  desc: string;
}[] = [
  {
    icon: "capacity",
    label: "Capacity",
    value: "1 200+",
    desc: "Seats across multiple halls",
  },
  {
    icon: "halls",
    label: "Conference Halls",
    value: "8",
    desc: "Equipped with AV systems",
  },
  {
    icon: "workshops",
    label: "Workshop Rooms",
    value: "12",
    desc: "Hands-on session spaces",
  },
  {
    icon: "wifi",
    label: "High-Speed WiFi",
    value: "1 Gbps",
    desc: "Full venue coverage",
  },
  {
    icon: "parking",
    label: "Parking",
    value: "500+",
    desc: "Free secured spots",
  },
  {
    icon: "catering",
    label: "Catering",
    value: "3",
    desc: "On-site restaurants",
  },
];

export const VENUE_MAPS = [
  {
    src: "/venue/map-floor-0.png",
    label: "Ground Floor",
  },
  {
    src: "/venue/map-floor-1.png",
    label: "First Floor",
  },
];

export const TUNISIA_GALLERY = [
  "/venue/tunisia-1.jpg",
  "/venue/tunisia-2.jpg",
  "/venue/tunisia-3.jpg",
  "/venue/tunisia-4.jpg",
  "/venue/tunisia-5.jpg",
  "/venue/tunisia-6.jpg",
];

export const VISA_FREE = [
  "Algeria",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Austria",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belgium",
  "Belize",
  "Benin",
  "Bosnia and Herzegovina",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Estonia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Germany",
  "Greece",
  "Guatemala",
  "Guinea",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kenya",
  "Kuwait",
  "Latvia",
  "Lebanon",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Monaco",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Netherlands",
  "New Zealand",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Panama",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "San Marino",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Tanzania",
  "Thailand",
  "Togo",
  "Trinidad and Tobago",
  "Turkey",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const CURRENCIES: Record<string, { name: string; rate: number }> = {
  USD: { name: "US Dollar", rate: 3.12 },
  EUR: { name: "Euro", rate: 3.42 },
  GBP: { name: "British Pound", rate: 3.95 },
  CAD: { name: "Canadian Dollar", rate: 2.28 },
  AED: { name: "UAE Dirham", rate: 0.85 },
  SAR: { name: "Saudi Riyal", rate: 0.83 },
  JPY: { name: "Japanese Yen", rate: 0.021 },
  INR: { name: "Indian Rupee", rate: 0.037 },
  CNY: { name: "Chinese Yuan", rate: 0.43 },
  MAD: { name: "Moroccan Dirham", rate: 0.31 },
  EGP: { name: "Egyptian Pound", rate: 0.064 },
  DZD: { name: "Algerian Dinar", rate: 0.023 },
  LYD: { name: "Libyan Dinar", rate: 0.65 },
};

export const FLOATING_FLAGS = [
  { code: "tn", name: "Tunisia", x: "8%", y: "18%" },
  { code: "dz", name: "Algeria", x: "22%", y: "7%" },
  { code: "de", name: "Germany", x: "42%", y: "2%" },
  { code: "fr", name: "France", x: "64%", y: "7%" },
  { code: "it", name: "Italy", x: "80%", y: "19%" },

  { code: "ma", name: "Morocco", x: "5%", y: "39%" },
  { code: "in", name: "India", x: "18%", y: "43%" },
  { code: "es", name: "Spain", x: "86%", y: "38%" },
  { code: "tr", name: "Turkey", x: "94%", y: "53%" },

  { code: "jp", name: "Japan", x: "9%", y: "64%" },
  { code: "kr", name: "South Korea", x: "23%", y: "81%" },
  { code: "br", name: "Brazil", x: "48%", y: "90%" },
  { code: "ae", name: "United Arab Emirates", x: "70%", y: "82%" },
  { code: "us", name: "United States", x: "84%", y: "64%" },

  { code: "gb", name: "United Kingdom", x: "35%", y: "24%" },
  { code: "ca", name: "Canada", x: "60%", y: "25%" },
  { code: "sa", name: "Saudi Arabia", x: "32%", y: "69%" },
  { code: "eg", name: "Egypt", x: "62%", y: "68%" },
];

export const DISCOVER_TAGS = [
  "Beaches",
  "Desert",
  "History",
  "Culture",
  "Cuisine",
  "Architecture",
];